apiVersion: apps/v1
kind: Deployment
metadata:
  name: akswf
  labels:
    app: akswf
  namespace: namespace-workflow-1689166566481
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akswf
  template:
    metadata:
      labels:
        app: akswf
    spec:
      containers:
        - name: akswf
          image: aksfuncazurecontainerregistry.azurecr.io/azurefunctioncontainerimage:latest
          ports:
            - containerPort: 5000